export const tableData = [
        {
            "id": "265",
            "categories": [
                "Buyer"
            ],
            "createdAt": "2024-02-12T06:01:16.249Z",
            "updatedAt": "2024-02-12T06:01:16.249Z",
            "name": "ertetwer",
            "shortCode": "P00134",
            "birthDate": null,
            "registrationDate": "2024-02-12T06:01:03.532Z",
            "email1": "rete@gmail.com",
            "email2": null,
            "contactPersonName": null,
            "mobileNo": null,
            "phoneNo": null,
            "country": "4",
            "zipCode": null,
            "faxNo": null,
            "isActive": true,
            "employeeId": null,
            "companyId": "1",
            "departmentId": null,
            "businessTypeId": null,
            "premises": null,
            "businessTypeName": null,
            "loginType": null,
            "assistantSalesPersonId": null,
            "mobileNoCc": "IN",
            "phoneNoCc": null,
            "phoneNoNdc": null,
            "faxNoNdc": null,
            "faxNoCc": null,
            "updatedByClient": null,
            "code": null,
            "codeTime": null,
            "multipleDepartmentId": [
                "SSPL-Diamond new",
                "computer"
            ],
            "gstNo": null,
            "remark": null,
            "additionalDiscount": null,
            "additionalDiscountRound": null,
            "employee": null,
            "Country": {
                "id": "4",
                "countryName": "Algeria"
            },
            "assistantSalesPerson": null,
            "TermsDetails": []
        },
        {
            "id": "264",
            "categories": [
                "Buyer",
                "Employee"
            ],
            "createdAt": "2024-02-11T08:46:44.386Z",
            "updatedAt": "2024-02-11T08:46:44.386Z",
            "name": "mayank agrawal",
            "shortCode": "P00133",
            "birthDate": null,
            "registrationDate": "2024-02-11T08:45:59.716Z",
            "email1": "mayank@gmail.com",
            "email2": null,
            "contactPersonName": null,
            "mobileNo": null,
            "phoneNo": null,
            "country": "101",
            "zipCode": null,
            "faxNo": null,
            "isActive": true,
            "employeeId": null,
            "companyId": "86",
            "departmentId": "1",
            "businessTypeId": "2190",
            "premises": null,
            "businessTypeName": "JEWELLERY MANUFACTURER",
            "loginType": null,
            "assistantSalesPersonId": null,
            "mobileNoCc": "IN",
            "phoneNoCc": null,
            "phoneNoNdc": null,
            "faxNoNdc": null,
            "faxNoCc": null,
            "updatedByClient": null,
            "code": null,
            "codeTime": null,
            "multipleDepartmentId": [
                "SSPL-Diamond new",
                "computer"
            ],
            "gstNo": null,
            "remark": null,
            "additionalDiscount": null,
            "additionalDiscountRound": null,
            "employee": null,
            "Country": {
                "id": "101",
                "countryName": "India"
            },
            "assistantSalesPerson": null,
            "TermsDetails": [
                {
                    "id": "199",
                    "refId": "264",
                    "currencyId": "2412",
                    "currencyPercentage": 2.5,
                    "deliveryTypeId": null,
                    "deliveryDays": null,
                    "dayTermsId": "2464",
                    "dayTermsPercentage": 0.5,
                    "extraDollar": null,
                    "extraPercentage": null,
                    "rapPercentage": null,
                    "creditLimit": null,
                    "memoLimit": null,
                    "isDefault": true,
                    "aadat": [],
                    "broker": [],
                    "totalPercentage": 3,
                    "isVerified": false,
                    "verifiedTime": null,
                    "editTermsId": null,
                    "verifiedBy": null,
                    "editStatus": false,
                    "termName": "COD (3) HKD  No Aadat No Broker",
                    "accountName": "mayank agrawal",
                    "currencyName": "HKD",
                    "deliveryTypeName": null,
                    "dayTermsName": "COD",
                    "totalPercentageFinal": 3
                }
            ]
        },
        {
            "id": "256",
            "categories": [
                "Buyer"
            ],
            "createdAt": "2024-02-08T13:42:54.263Z",
            "updatedAt": "2024-02-08T13:42:54.263Z",
            "name": "Star Diamond",
            "shortCode": "P00131",
            "birthDate": null,
            "registrationDate": "2024-02-08T13:42:12.120Z",
            "email1": "stard@gmail.com",
            "email2": null,
            "contactPersonName": null,
            "mobileNo": null,
            "phoneNo": null,
            "country": "101",
            "zipCode": null,
            "faxNo": null,
            "isActive": true,
            "employeeId": null,
            "companyId": "86",
            "departmentId": "1",
            "businessTypeId": "2188",
            "premises": null,
            "businessTypeName": "DIAMOND WHOLESALER",
            "loginType": null,
            "assistantSalesPersonId": null,
            "mobileNoCc": "IN",
            "phoneNoCc": null,
            "phoneNoNdc": null,
            "faxNoNdc": null,
            "faxNoCc": null,
            "updatedByClient": null,
            "code": null,
            "codeTime": null,
            "multipleDepartmentId": null,
            "gstNo": null,
            "remark": null,
            "additionalDiscount": null,
            "additionalDiscountRound": null,
            "employee": null,
            "Country": {
                "id": "101",
                "countryName": "India"
            },
            "assistantSalesPerson": null,
            "TermsDetails": []
        },
        {
            "id": "248",
            "categories": [
                "Buyer"
            ],
            "createdAt": "2024-02-06T12:27:50.211Z",
            "updatedAt": "2024-02-06T12:27:50.211Z",
            "name": "ANKIT GEMS INC",
            "shortCode": "P00123",
            "birthDate": null,
            "registrationDate": "2024-02-06T12:26:28.449Z",
            "email1": "viral.goradia@ankitgems.com",
            "email2": null,
            "contactPersonName": "VIRAL GORADIA",
            "mobileNo": null,
            "phoneNo": null,
            "country": "233",
            "zipCode": null,
            "faxNo": null,
            "isActive": true,
            "employeeId": null,
            "companyId": "86",
            "departmentId": "1",
            "businessTypeId": "2196",
            "premises": null,
            "businessTypeName": "DIAMOND TRADER",
            "loginType": null,
            "assistantSalesPersonId": null,
            "mobileNoCc": "US",
            "phoneNoCc": null,
            "phoneNoNdc": null,
            "faxNoNdc": null,
            "faxNoCc": null,
            "updatedByClient": null,
            "code": null,
            "codeTime": null,
            "multipleDepartmentId": [
                "SSPL-Diamond new"
            ],
            "gstNo": null,
            "remark": null,
            "additionalDiscount": null,
            "additionalDiscountRound": null,
            "employee": null,
            "Country": {
                "id": "233",
                "countryName": "United States Of America"
            },
            "assistantSalesPerson": null,
            "TermsDetails": [
                {
                    "id": "195",
                    "refId": "248",
                    "currencyId": "2412",
                    "currencyPercentage": 2.5,
                    "deliveryTypeId": null,
                    "deliveryDays": null,
                    "dayTermsId": "2459",
                    "dayTermsPercentage": 1,
                    "extraDollar": null,
                    "extraPercentage": null,
                    "rapPercentage": null,
                    "creditLimit": null,
                    "memoLimit": null,
                    "isDefault": true,
                    "aadat": [
                        {
                            "id": 229,
                            "name": "Adinath",
                            "commission": 1
                        }
                    ],
                    "broker": [
                        {
                            "id": 183,
                            "name": "Antique Diamonds",
                            "commission": 2
                        }
                    ],
                    "totalPercentage": 6.5,
                    "isVerified": true,
                    "verifiedTime": null,
                    "editTermsId": null,
                    "verifiedBy": null,
                    "editStatus": false,
                    "termName": "30 DAYS (6.5) HKD  Adinath (1) Antique Diamonds (2)",
                    "accountName": "ANKIT GEMS INC",
                    "currencyName": "HKD",
                    "deliveryTypeName": null,
                    "dayTermsName": "30 DAYS",
                    "totalPercentageFinal": 6.5
                }
            ]
        },
        {
            "id": "247",
            "categories": [
                "Buyer"
            ],
            "createdAt": "2024-02-06T08:47:58.611Z",
            "updatedAt": "2024-02-09T06:18:14.750Z",
            "name": "Sarvadhi SOlutions",
            "shortCode": "P00122",
            "birthDate": null,
            "registrationDate": "2024-02-06T08:45:33.774Z",
            "email1": "hemal@sarvadhi.com",
            "email2": "hemalmoradiya@gmail.com",
            "contactPersonName": "9099879018",
            "mobileNo": "9090909090",
            "phoneNo": "1234567878",
            "country": "101",
            "zipCode": null,
            "faxNo": "7876787878",
            "isActive": true,
            "employeeId": "43",
            "companyId": "86",
            "departmentId": "1",
            "businessTypeId": "2191",
            "premises": null,
            "businessTypeName": "DIAMOND MANUFACTURER",
            "loginType": null,
            "assistantSalesPersonId": null,
            "mobileNoCc": "IN",
            "phoneNoCc": "0",
            "phoneNoNdc": "261",
            "faxNoNdc": "123",
            "faxNoCc": "1",
            "updatedByClient": null,
            "code": null,
            "codeTime": null,
            "multipleDepartmentId": [
                "SSPL-Diamond new"
            ],
            "gstNo": "123456789012111",
            "remark": null,
            "additionalDiscount": null,
            "additionalDiscountRound": null,
            "employee": {
                "name": "viren ashodaria"
            },
            "Country": {
                "id": "101",
                "countryName": "India"
            },
            "assistantSalesPerson": null,
            "TermsDetails": [
                {
                    "id": "196",
                    "refId": "247",
                    "currencyId": "2411",
                    "currencyPercentage": 1,
                    "deliveryTypeId": null,
                    "deliveryDays": null,
                    "dayTermsId": "2459",
                    "dayTermsPercentage": 1,
                    "extraDollar": null,
                    "extraPercentage": null,
                    "rapPercentage": null,
                    "creditLimit": null,
                    "memoLimit": null,
                    "isDefault": true,
                    "aadat": [
                        {
                            "id": 221,
                            "name": "hardik",
                            "commission": 12
                        }
                    ],
                    "broker": [],
                    "totalPercentage": 14,
                    "isVerified": false,
                    "verifiedTime": null,
                    "editTermsId": null,
                    "verifiedBy": null,
                    "editStatus": false,
                    "termName": "30 DAYS (14) INR  hardik (12) No Broker",
                    "accountName": "Sarvadhi SOlutions",
                    "currencyName": "INR",
                    "deliveryTypeName": null,
                    "dayTermsName": "30 DAYS",
                    "totalPercentageFinal": 14
                },
                {
                    "id": "193",
                    "refId": "247",
                    "currencyId": "2412",
                    "currencyPercentage": 2.5,
                    "deliveryTypeId": null,
                    "deliveryDays": null,
                    "dayTermsId": "2453",
                    "dayTermsPercentage": null,
                    "extraDollar": null,
                    "extraPercentage": null,
                    "rapPercentage": null,
                    "creditLimit": null,
                    "memoLimit": null,
                    "isDefault": false,
                    "aadat": [
                        {
                            "id": 229,
                            "name": "Adinath",
                            "commission": 0
                        }
                    ],
                    "broker": [],
                    "totalPercentage": 2.5,
                    "isVerified": false,
                    "verifiedTime": null,
                    "editTermsId": null,
                    "verifiedBy": null,
                    "editStatus": false,
                    "termName": "ADVANCE BID (2.5) HKD  Adinath (0) No Broker",
                    "accountName": "Sarvadhi SOlutions",
                    "currencyName": "HKD",
                    "deliveryTypeName": null,
                    "dayTermsName": "ADVANCE BID",
                    "totalPercentageFinal": 2.5
                },
                {
                    "id": "194",
                    "refId": "247",
                    "currencyId": "2412",
                    "currencyPercentage": 2.5,
                    "deliveryTypeId": null,
                    "deliveryDays": null,
                    "dayTermsId": "2453",
                    "dayTermsPercentage": null,
                    "extraDollar": null,
                    "extraPercentage": null,
                    "rapPercentage": null,
                    "creditLimit": null,
                    "memoLimit": null,
                    "isDefault": false,
                    "aadat": [
                        {
                            "id": 229,
                            "name": "Adinath",
                            "commission": 20
                        }
                    ],
                    "broker": [
                        {
                            "id": 209,
                            "name": "Paras Broker Buyer",
                            "commission": 10
                        }
                    ],
                    "totalPercentage": 32.5,
                    "isVerified": false,
                    "verifiedTime": null,
                    "editTermsId": null,
                    "verifiedBy": null,
                    "editStatus": false,
                    "termName": "ADVANCE BID (32.5) HKD  Adinath (20) Paras Broker Buyer (10)",
                    "accountName": "Sarvadhi SOlutions",
                    "currencyName": "HKD",
                    "deliveryTypeName": null,
                    "dayTermsName": "ADVANCE BID",
                    "totalPercentageFinal": 32.5
                }
            ]
        },
        {
            "id": "246",
            "categories": [
                "Employee"
            ],
            "createdAt": "2024-02-06T05:42:40.278Z",
            "updatedAt": "2024-02-08T05:06:39.886Z",
            "name": "SACHIN BHAYAJE",
            "shortCode": "P00121",
            "birthDate": "1999-02-04T00:00:00.000Z",
            "registrationDate": "2024-02-06T05:40:40.870Z",
            "email1": "sachin@gmail.com",
            "email2": null,
            "contactPersonName": "SACHIN contact",
            "mobileNo": "9619495982",
            "phoneNo": null,
            "country": "101",
            "zipCode": null,
            "faxNo": null,
            "isActive": true,
            "employeeId": null,
            "companyId": "86",
            "departmentId": "1",
            "businessTypeId": "2189",
            "premises": null,
            "businessTypeName": "OTHER",
            "loginType": null,
            "assistantSalesPersonId": null,
            "mobileNoCc": "IN",
            "phoneNoCc": null,
            "phoneNoNdc": null,
            "faxNoNdc": null,
            "faxNoCc": null,
            "updatedByClient": null,
            "code": null,
            "codeTime": null,
            "multipleDepartmentId": [],
            "gstNo": null,
            "remark": null,
            "additionalDiscount": null,
            "additionalDiscountRound": null,
            "employee": null,
            "Country": {
                "id": "101",
                "countryName": "India"
            },
            "assistantSalesPerson": null,
            "TermsDetails": [
                {
                    "id": "192",
                    "refId": "246",
                    "currencyId": "2413",
                    "currencyPercentage": null,
                    "deliveryTypeId": null,
                    "deliveryDays": null,
                    "dayTermsId": "2464",
                    "dayTermsPercentage": 0.5,
                    "extraDollar": null,
                    "extraPercentage": null,
                    "rapPercentage": null,
                    "creditLimit": null,
                    "memoLimit": null,
                    "isDefault": true,
                    "aadat": [],
                    "broker": [],
                    "totalPercentage": 0.5,
                    "isVerified": true,
                    "verifiedTime": null,
                    "editTermsId": null,
                    "verifiedBy": null,
                    "editStatus": false,
                    "termName": "COD (0.5) USD  No Aadat No Broker",
                    "accountName": "SACHIN BHAYAJE",
                    "currencyName": "USD",
                    "deliveryTypeName": null,
                    "dayTermsName": "COD",
                    "totalPercentageFinal": 0.5
                }
            ]
        },
        {
            "id": "245",
            "categories": [
                "Aadat",
                "Broker",
                "Buyer"
            ],
            "createdAt": "2024-02-05T18:34:39.602Z",
            "updatedAt": "2024-02-05T18:35:52.058Z",
            "name": "Mayur Solanki",
            "shortCode": "P00120",
            "birthDate": "1996-08-10T00:00:00.000Z",
            "registrationDate": "2024-02-05T00:00:00.000Z",
            "email1": "Mayur@sarvadhi.com",
            "email2": null,
            "contactPersonName": null,
            "mobileNo": null,
            "phoneNo": null,
            "country": "101",
            "zipCode": null,
            "faxNo": null,
            "isActive": true,
            "employeeId": null,
            "companyId": "86",
            "departmentId": "1",
            "businessTypeId": null,
            "premises": null,
            "businessTypeName": null,
            "loginType": null,
            "assistantSalesPersonId": null,
            "mobileNoCc": "IN",
            "phoneNoCc": null,
            "phoneNoNdc": null,
            "faxNoNdc": null,
            "faxNoCc": null,
            "updatedByClient": null,
            "code": null,
            "codeTime": null,
            "multipleDepartmentId": [
                "SSPL-Diamond new"
            ],
            "gstNo": null,
            "remark": null,
            "additionalDiscount": null,
            "additionalDiscountRound": null,
            "employee": null,
            "Country": {
                "id": "101",
                "countryName": "India"
            },
            "assistantSalesPerson": null,
            "TermsDetails": []
        },
        {
            "id": "243",
            "categories": [
                "Buyer"
            ],
            "createdAt": "2024-02-05T09:30:17.946Z",
            "updatedAt": "2024-02-05T09:30:35.042Z",
            "name": "uniqe gems",
            "shortCode": "P00118",
            "birthDate": null,
            "registrationDate": "2024-02-05T09:29:38.058Z",
            "email1": "may2651@gmail.com",
            "email2": null,
            "contactPersonName": null,
            "mobileNo": "7878909078",
            "phoneNo": null,
            "country": "101",
            "zipCode": null,
            "faxNo": null,
            "isActive": true,
            "employeeId": "137",
            "companyId": "86",
            "departmentId": "1",
            "businessTypeId": "2191",
            "premises": null,
            "businessTypeName": "DIAMOND MANUFACTURER",
            "loginType": null,
            "assistantSalesPersonId": null,
            "mobileNoCc": "IN",
            "phoneNoCc": null,
            "phoneNoNdc": null,
            "faxNoNdc": null,
            "faxNoCc": null,
            "updatedByClient": null,
            "code": null,
            "codeTime": null,
            "multipleDepartmentId": [
                "SSPL-Diamond new"
            ],
            "gstNo": null,
            "remark": null,
            "additionalDiscount": null,
            "additionalDiscountRound": null,
            "employee": {
                "name": "HRK Diamonds"
            },
            "Country": {
                "id": "101",
                "countryName": "India"
            },
            "assistantSalesPerson": null,
            "TermsDetails": []
        },
        {
            "id": "241",
            "categories": [
                "Vendor"
            ],
            "createdAt": "2024-02-05T04:37:20.611Z",
            "updatedAt": "2024-02-05T04:41:51.708Z",
            "name": "SRK Diamonds pvt ltd.",
            "shortCode": "P00116",
            "birthDate": "1970-10-06T00:00:00.000Z",
            "registrationDate": null,
            "email1": "govinddholakiya@gmail.com",
            "email2": "srk@gmail.in",
            "contactPersonName": "Govind bhagat",
            "mobileNo": "9956313457",
            "phoneNo": "8562314523",
            "country": "101",
            "zipCode": null,
            "faxNo": null,
            "isActive": true,
            "employeeId": "43",
            "companyId": "86",
            "departmentId": "1",
            "businessTypeId": "2191",
            "premises": null,
            "businessTypeName": "DIAMOND MANUFACTURER",
            "loginType": null,
            "assistantSalesPersonId": "234",
            "mobileNoCc": "IN",
            "phoneNoCc": null,
            "phoneNoNdc": null,
            "faxNoNdc": null,
            "faxNoCc": null,
            "updatedByClient": null,
            "code": null,
            "codeTime": null,
            "multipleDepartmentId": [
                "SSPL-Diamond new"
            ],
            "gstNo": null,
            "remark": null,
            "additionalDiscount": null,
            "additionalDiscountRound": null,
            "employee": {
                "name": "viren ashodaria"
            },
            "Country": {
                "id": "101",
                "countryName": "India"
            },
            "assistantSalesPerson": {
                "name": "ARYAN DIAMONDS"
            },
            "TermsDetails": [
                {
                    "id": "179",
                    "refId": "241",
                    "currencyId": "2411",
                    "currencyPercentage": 1,
                    "deliveryTypeId": null,
                    "deliveryDays": null,
                    "dayTermsId": "2464",
                    "dayTermsPercentage": 0.5,
                    "extraDollar": null,
                    "extraPercentage": null,
                    "rapPercentage": null,
                    "creditLimit": null,
                    "memoLimit": null,
                    "isDefault": true,
                    "aadat": [
                        {
                            "id": 206,
                            "name": "Ramesh Broker",
                            "commission": 1.2
                        }
                    ],
                    "broker": [
                        {
                            "id": 209,
                            "name": "Paras Broker Buyer",
                            "commission": 3.5
                        }
                    ],
                    "totalPercentage": 6.2,
                    "isVerified": true,
                    "verifiedTime": null,
                    "editTermsId": null,
                    "verifiedBy": null,
                    "editStatus": false,
                    "termName": "COD (6.2) INR  Ramesh Broker (1.2) Paras Broker Buyer (3.5)",
                    "accountName": "SRK diamonds pvt ltd.",
                    "currencyName": "INR",
                    "deliveryTypeName": null,
                    "dayTermsName": "COD",
                    "totalPercentageFinal": 6.2
                }
            ]
        },
        {
            "id": "234",
            "categories": [
                "Employee",
                "Mfg"
            ],
            "createdAt": "2024-02-02T04:49:55.893Z",
            "updatedAt": "2024-02-05T05:28:11.997Z",
            "name": "ARYAN DIAMONDS",
            "shortCode": "P00109",
            "birthDate": null,
            "registrationDate": null,
            "email1": "arayn@gmail.com",
            "email2": null,
            "contactPersonName": "Aryan Mehta",
            "mobileNo": "9999988888",
            "phoneNo": null,
            "country": "3",
            "zipCode": null,
            "faxNo": null,
            "isActive": true,
            "employeeId": "234",
            "companyId": "86",
            "departmentId": "1",
            "businessTypeId": "2188",
            "premises": null,
            "businessTypeName": "DIAMOND WHOLESALER",
            "loginType": null,
            "assistantSalesPersonId": "137",
            "mobileNoCc": "IN",
            "phoneNoCc": null,
            "phoneNoNdc": null,
            "faxNoNdc": null,
            "faxNoCc": null,
            "updatedByClient": null,
            "code": null,
            "codeTime": null,
            "multipleDepartmentId": [
                "SSPL-Diamond new"
            ],
            "gstNo": null,
            "remark": null,
            "additionalDiscount": null,
            "additionalDiscountRound": null,
            "employee": {
                "name": "ARYAN DIAMONDS"
            },
            "Country": {
                "id": "3",
                "countryName": "Albania"
            },
            "assistantSalesPerson": {
                "name": "HRK Diamonds"
            },
            "TermsDetails": [
                {
                    "id": "176",
                    "refId": "234",
                    "currencyId": "2412",
                    "currencyPercentage": 2.5,
                    "deliveryTypeId": null,
                    "deliveryDays": null,
                    "dayTermsId": "2457",
                    "dayTermsPercentage": null,
                    "extraDollar": null,
                    "extraPercentage": null,
                    "rapPercentage": null,
                    "creditLimit": null,
                    "memoLimit": null,
                    "isDefault": true,
                    "aadat": [],
                    "broker": [],
                    "totalPercentage": 2.5,
                    "isVerified": true,
                    "verifiedTime": null,
                    "editTermsId": null,
                    "verifiedBy": null,
                    "editStatus": false,
                    "termName": "7 DAYS (2.5) HKD  No Aadat No Broker",
                    "accountName": "ARYAN DIAMONDS",
                    "currencyName": "HKD",
                    "deliveryTypeName": null,
                    "dayTermsName": "7 DAYS",
                    "totalPercentageFinal": 2.5
                }
            ]
        },
        {
            "id": "231",
            "categories": [
                "Employee"
            ],
            "createdAt": "2024-02-01T07:22:28.242Z",
            "updatedAt": "2024-02-05T19:21:12.185Z",
            "name": "Faizal nawab",
            "shortCode": "P00106",
            "birthDate": "1996-10-10T00:00:00.000Z",
            "registrationDate": "2024-02-06T00:00:00.000Z",
            "email1": "refrwa@gmail.com",
            "email2": null,
            "contactPersonName": "Mayur Solanki",
            "mobileNo": "7676789789",
            "phoneNo": null,
            "country": "39",
            "zipCode": null,
            "faxNo": null,
            "isActive": true,
            "employeeId": "137",
            "companyId": "1",
            "departmentId": null,
            "businessTypeId": null,
            "premises": null,
            "businessTypeName": null,
            "loginType": null,
            "assistantSalesPersonId": "175",
            "mobileNoCc": "CA",
            "phoneNoCc": null,
            "phoneNoNdc": null,
            "faxNoNdc": null,
            "faxNoCc": null,
            "updatedByClient": null,
            "code": null,
            "codeTime": null,
            "multipleDepartmentId": [
                "SSPL-Diamond new"
            ],
            "gstNo": null,
            "remark": null,
            "additionalDiscount": null,
            "additionalDiscountRound": null,
            "employee": {
                "name": "HRK Diamonds"
            },
            "Country": {
                "id": "39",
                "countryName": "Canada"
            },
            "assistantSalesPerson": {
                "name": "Mega Gems"
            },
            "TermsDetails": [
                {
                    "id": "172",
                    "refId": "231",
                    "currencyId": "2412",
                    "currencyPercentage": 2.5,
                    "deliveryTypeId": null,
                    "deliveryDays": null,
                    "dayTermsId": "2468",
                    "dayTermsPercentage": null,
                    "extraDollar": null,
                    "extraPercentage": null,
                    "rapPercentage": null,
                    "creditLimit": null,
                    "memoLimit": null,
                    "isDefault": true,
                    "aadat": [],
                    "broker": [],
                    "totalPercentage": 2.5,
                    "isVerified": true,
                    "verifiedTime": null,
                    "editTermsId": null,
                    "verifiedBy": null,
                    "editStatus": null,
                    "termName": "LC (2.5) HKD  No Aadat No Broker",
                    "accountName": "fdd",
                    "currencyName": "HKD",
                    "deliveryTypeName": null,
                    "dayTermsName": "LC",
                    "totalPercentageFinal": 2.5
                }
            ]
        },
        {
            "id": "229",
            "categories": [
                "Aadat"
            ],
            "createdAt": "2024-02-01T07:19:13.722Z",
            "updatedAt": "2024-02-06T11:33:28.020Z",
            "name": "Adinath",
            "shortCode": "P00104",
            "birthDate": null,
            "registrationDate": null,
            "email1": "ewe@gmail.com",
            "email2": null,
            "contactPersonName": null,
            "mobileNo": null,
            "phoneNo": null,
            "country": "1",
            "zipCode": null,
            "faxNo": null,
            "isActive": false,
            "employeeId": null,
            "companyId": "1",
            "departmentId": null,
            "businessTypeId": null,
            "premises": null,
            "businessTypeName": null,
            "loginType": null,
            "assistantSalesPersonId": null,
            "mobileNoCc": "IN",
            "phoneNoCc": null,
            "phoneNoNdc": null,
            "faxNoNdc": null,
            "faxNoCc": null,
            "updatedByClient": null,
            "code": null,
            "codeTime": null,
            "multipleDepartmentId": [
                "SSPL-Diamond new"
            ],
            "gstNo": null,
            "remark": null,
            "additionalDiscount": null,
            "additionalDiscountRound": null,
            "employee": null,
            "Country": {
                "id": "1",
                "countryName": "Afghanistan"
            },
            "assistantSalesPerson": null,
            "TermsDetails": []
        },
        {
            "id": "221",
            "categories": [
                "Aadat"
            ],
            "createdAt": "2024-01-30T10:45:03.479Z",
            "updatedAt": "2024-02-05T04:45:41.970Z",
            "name": "hardik",
            "shortCode": "P00100",
            "birthDate": "2024-01-23T00:00:00.000Z",
            "registrationDate": null,
            "email1": "carzyMan@pirolsnet.com",
            "email2": "xz3k3x6t@pirolsnet.com",
            "contactPersonName": "hardik",
            "mobileNo": null,
            "phoneNo": null,
            "country": "226",
            "zipCode": null,
            "faxNo": null,
            "isActive": false,
            "employeeId": null,
            "companyId": "1",
            "departmentId": null,
            "businessTypeId": "2191",
            "premises": null,
            "businessTypeName": "DIAMOND MANUFACTURER",
            "loginType": null,
            "assistantSalesPersonId": null,
            "mobileNoCc": "IN",
            "phoneNoCc": null,
            "phoneNoNdc": null,
            "faxNoNdc": null,
            "faxNoCc": null,
            "updatedByClient": null,
            "code": null,
            "codeTime": null,
            "multipleDepartmentId": [
                "SSPL-Diamond new"
            ],
            "gstNo": null,
            "remark": null,
            "additionalDiscount": null,
            "additionalDiscountRound": null,
            "employee": null,
            "Country": {
                "id": "226",
                "countryName": "Turkmenistan"
            },
            "assistantSalesPerson": null,
            "TermsDetails": [
                {
                    "id": "160",
                    "refId": "221",
                    "currencyId": "2413",
                    "currencyPercentage": null,
                    "deliveryTypeId": null,
                    "deliveryDays": 44,
                    "dayTermsId": "2457",
                    "dayTermsPercentage": null,
                    "extraDollar": null,
                    "extraPercentage": 4,
                    "rapPercentage": 4,
                    "creditLimit": null,
                    "memoLimit": null,
                    "isDefault": true,
                    "aadat": [],
                    "broker": [],
                    "totalPercentage": 4,
                    "isVerified": true,
                    "verifiedTime": null,
                    "editTermsId": null,
                    "verifiedBy": null,
                    "editStatus": null,
                    "termName": "7 DAYS (4) USD 4 No Aadat No Broker",
                    "accountName": "hardik",
                    "currencyName": "USD",
                    "deliveryTypeName": null,
                    "dayTermsName": "7 DAYS",
                    "totalPercentageFinal": 4
                },
                {
                    "id": "170",
                    "refId": "221",
                    "currencyId": "2412",
                    "currencyPercentage": 2.5,
                    "deliveryTypeId": null,
                    "deliveryDays": null,
                    "dayTermsId": "2458",
                    "dayTermsPercentage": 0.5,
                    "extraDollar": null,
                    "extraPercentage": null,
                    "rapPercentage": null,
                    "creditLimit": null,
                    "memoLimit": null,
                    "isDefault": false,
                    "aadat": [
                        {
                            "id": 187,
                            "name": "Suresh Broker",
                            "commission": 1
                        },
                        {
                            "id": 206,
                            "name": "Ramesh Broker",
                            "commission": 2
                        }
                    ],
                    "broker": [],
                    "totalPercentage": 6,
                    "isVerified": true,
                    "verifiedTime": null,
                    "editTermsId": null,
                    "verifiedBy": null,
                    "editStatus": null,
                    "termName": "15DAYS (6) HKD  Suresh Broker (1) Ramesh Broker (2) No Broker",
                    "accountName": "hardik",
                    "currencyName": "HKD",
                    "deliveryTypeName": null,
                    "dayTermsName": "15DAYS",
                    "totalPercentageFinal": 6
                }
            ]
        },
        {
            "id": "217",
            "categories": [
                "Broker"
            ],
            "createdAt": "2024-01-30T08:57:44.329Z",
            "updatedAt": "2024-01-30T08:57:44.329Z",
            "name": "Nayda Newman",
            "shortCode": "P00096",
            "birthDate": "2024-01-17T00:00:00.000Z",
            "registrationDate": "2024-01-09T00:00:00.000Z",
            "email1": "vudireni@mailinator.com",
            "email2": "qygywabyz@mailinator.com",
            "contactPersonName": "Diana Melton",
            "mobileNo": "9999955555",
            "phoneNo": "7777755555",
            "country": "3",
            "zipCode": null,
            "faxNo": "5555599999",
            "isActive": true,
            "employeeId": "175",
            "companyId": "86",
            "departmentId": "1",
            "businessTypeId": "2196",
            "premises": null,
            "businessTypeName": "DIAMOND TRADER",
            "loginType": null,
            "assistantSalesPersonId": "175",
            "mobileNoCc": "AX",
            "phoneNoCc": "12",
            "phoneNoNdc": "60",
            "faxNoNdc": "81",
            "faxNoCc": "14",
            "updatedByClient": null,
            "code": null,
            "codeTime": null,
            "multipleDepartmentId": [],
            "gstNo": "dsgdsg51651651s",
            "remark": "demo test",
            "additionalDiscount": null,
            "additionalDiscountRound": null,
            "employee": {
                "name": "Mega Gems"
            },
            "Country": {
                "id": "3",
                "countryName": "Albania"
            },
            "assistantSalesPerson": {
                "name": "Mega Gems"
            },
            "TermsDetails": []
        },
        {
            "id": "213",
            "categories": [
                "Broker"
            ],
            "createdAt": "2024-01-30T08:35:56.082Z",
            "updatedAt": "2024-02-07T06:20:58.030Z",
            "name": "om gems one",
            "shortCode": "P00092",
            "birthDate": null,
            "registrationDate": "2024-02-07T06:19:59.129Z",
            "email1": "omgemsone@yopmail.com",
            "email2": null,
            "contactPersonName": null,
            "mobileNo": null,
            "phoneNo": null,
            "country": "101",
            "zipCode": null,
            "faxNo": null,
            "isActive": false,
            "employeeId": null,
            "companyId": "86",
            "departmentId": "1",
            "businessTypeId": null,
            "premises": null,
            "businessTypeName": null,
            "loginType": null,
            "assistantSalesPersonId": null,
            "mobileNoCc": "IN",
            "phoneNoCc": null,
            "phoneNoNdc": null,
            "faxNoNdc": null,
            "faxNoCc": null,
            "updatedByClient": null,
            "code": null,
            "codeTime": null,
            "multipleDepartmentId": [
                "SSPL-Diamond new",
                "computer"
            ],
            "gstNo": null,
            "remark": null,
            "additionalDiscount": null,
            "additionalDiscountRound": null,
            "employee": null,
            "Country": {
                "id": "101",
                "countryName": "India"
            },
            "assistantSalesPerson": null,
            "TermsDetails": []
        },
        {
            "id": "210",
            "categories": [
                "Broker",
                "Buyer"
            ],
            "createdAt": "2024-01-24T12:27:43.736Z",
            "updatedAt": "2024-02-01T11:02:51.682Z",
            "name": "Sarvadhi",
            "shortCode": "P00089",
            "birthDate": null,
            "registrationDate": null,
            "email1": "jatin@sarvadhi.com",
            "email2": null,
            "contactPersonName": "Jatin Dudhat",
            "mobileNo": "9913591275",
            "phoneNo": "1234567809",
            "country": "101",
            "zipCode": null,
            "faxNo": null,
            "isActive": true,
            "employeeId": "66",
            "companyId": "1",
            "departmentId": "1",
            "businessTypeId": "2191",
            "premises": null,
            "businessTypeName": null,
            "loginType": null,
            "assistantSalesPersonId": "66",
            "mobileNoCc": "IN",
            "phoneNoCc": null,
            "phoneNoNdc": null,
            "faxNoNdc": null,
            "faxNoCc": null,
            "updatedByClient": null,
            "code": null,
            "codeTime": null,
            "multipleDepartmentId": null,
            "gstNo": null,
            "remark": "Sarvadhi Employe",
            "additionalDiscount": null,
            "additionalDiscountRound": null,
            "employee": null,
            "Country": {
                "id": "101",
                "countryName": "India"
            },
            "assistantSalesPerson": null,
            "TermsDetails": [
                {
                    "id": "169",
                    "refId": "210",
                    "currencyId": "2411",
                    "currencyPercentage": 1,
                    "deliveryTypeId": null,
                    "deliveryDays": null,
                    "dayTermsId": "2458",
                    "dayTermsPercentage": 0.5,
                    "extraDollar": null,
                    "extraPercentage": null,
                    "rapPercentage": null,
                    "creditLimit": null,
                    "memoLimit": null,
                    "isDefault": false,
                    "aadat": [],
                    "broker": [],
                    "totalPercentage": 1.5,
                    "isVerified": true,
                    "verifiedTime": null,
                    "editTermsId": null,
                    "verifiedBy": null,
                    "editStatus": null,
                    "termName": "15DAYS (1.5) INR  No Aadat No Broker",
                    "accountName": "Sarvadhi",
                    "currencyName": "INR",
                    "deliveryTypeName": null,
                    "dayTermsName": "15DAYS",
                    "totalPercentageFinal": 1.5
                },
                {
                    "id": "173",
                    "refId": "210",
                    "currencyId": "2413",
                    "currencyPercentage": null,
                    "deliveryTypeId": null,
                    "deliveryDays": null,
                    "dayTermsId": "2463",
                    "dayTermsPercentage": null,
                    "extraDollar": null,
                    "extraPercentage": null,
                    "rapPercentage": null,
                    "creditLimit": null,
                    "memoLimit": null,
                    "isDefault": true,
                    "aadat": [],
                    "broker": [],
                    "totalPercentage": 0,
                    "isVerified": true,
                    "verifiedTime": null,
                    "editTermsId": null,
                    "verifiedBy": null,
                    "editStatus": false,
                    "termName": "ADVANCE HH (0) USD  No Aadat No Broker",
                    "accountName": "Sarvadhi",
                    "currencyName": "USD",
                    "deliveryTypeName": null,
                    "dayTermsName": "ADVANCE HH",
                    "totalPercentageFinal": 0
                },
                {
                    "id": "141",
                    "refId": "210",
                    "currencyId": "2411",
                    "currencyPercentage": 1,
                    "deliveryTypeId": null,
                    "deliveryDays": 30,
                    "dayTermsId": "2458",
                    "dayTermsPercentage": 0.5,
                    "extraDollar": null,
                    "extraPercentage": 1,
                    "rapPercentage": null,
                    "creditLimit": null,
                    "memoLimit": null,
                    "isDefault": false,
                    "aadat": [],
                    "broker": [
                        {
                            "id": 210,
                            "name": "Sarvadhi",
                            "commission": 0.5
                        }
                    ],
                    "totalPercentage": 3,
                    "isVerified": true,
                    "verifiedTime": null,
                    "editTermsId": null,
                    "verifiedBy": null,
                    "editStatus": null,
                    "termName": "15DAYS (3) INR 1 No Aadat Sarvadhi (0.5)",
                    "accountName": "Sarvadhi",
                    "currencyName": "INR",
                    "deliveryTypeName": null,
                    "dayTermsName": "15DAYS",
                    "totalPercentageFinal": 3
                }
            ]
        },
        {
            "id": "209",
            "categories": [
                "Broker",
                "Buyer"
            ],
            "createdAt": "2024-01-24T08:36:38.199Z",
            "updatedAt": "2024-02-02T05:39:21.318Z",
            "name": "Paras Broker Buyer",
            "shortCode": "P00088",
            "birthDate": "1991-06-20T00:00:00.000Z",
            "registrationDate": null,
            "email1": "paras.chodavadiya@gmail.com",
            "email2": null,
            "contactPersonName": "Paras",
            "mobileNo": "9033456752",
            "phoneNo": null,
            "country": "101",
            "zipCode": null,
            "faxNo": null,
            "isActive": true,
            "employeeId": "43",
            "companyId": "1",
            "departmentId": "1",
            "businessTypeId": "2191",
            "premises": null,
            "businessTypeName": null,
            "loginType": null,
            "assistantSalesPersonId": "175",
            "mobileNoCc": "IN",
            "phoneNoCc": null,
            "phoneNoNdc": null,
            "faxNoNdc": null,
            "faxNoCc": null,
            "updatedByClient": null,
            "code": null,
            "codeTime": null,
            "multipleDepartmentId": [],
            "gstNo": null,
            "remark": null,
            "additionalDiscount": null,
            "additionalDiscountRound": null,
            "employee": {
                "name": "viren ashodaria"
            },
            "Country": {
                "id": "101",
                "countryName": "India"
            },
            "assistantSalesPerson": {
                "name": "Mega Gems"
            },
            "TermsDetails": [
                {
                    "id": "197",
                    "refId": "209",
                    "currencyId": "2411",
                    "currencyPercentage": 1,
                    "deliveryTypeId": null,
                    "deliveryDays": null,
                    "dayTermsId": "2453",
                    "dayTermsPercentage": null,
                    "extraDollar": null,
                    "extraPercentage": 1,
                    "rapPercentage": 1,
                    "creditLimit": null,
                    "memoLimit": null,
                    "isDefault": true,
                    "aadat": [
                        {
                            "id": 229,
                            "name": "Adinath",
                            "commission": 1
                        }
                    ],
                    "broker": [
                        {
                            "id": 217,
                            "name": "Nayda Newman",
                            "commission": 1
                        }
                    ],
                    "totalPercentage": 4,
                    "isVerified": false,
                    "verifiedTime": null,
                    "editTermsId": null,
                    "verifiedBy": null,
                    "editStatus": false,
                    "termName": "ADVANCE BID (4) INR 1 Adinath (1) Nayda Newman (1)",
                    "accountName": "Paras Broker Buyer",
                    "currencyName": "INR",
                    "deliveryTypeName": null,
                    "dayTermsName": "ADVANCE BID",
                    "totalPercentageFinal": 4
                },
                {
                    "id": "139",
                    "refId": "209",
                    "currencyId": "2411",
                    "currencyPercentage": 1,
                    "deliveryTypeId": null,
                    "deliveryDays": null,
                    "dayTermsId": "2458",
                    "dayTermsPercentage": 0.5,
                    "extraDollar": null,
                    "extraPercentage": null,
                    "rapPercentage": null,
                    "creditLimit": null,
                    "memoLimit": null,
                    "isDefault": false,
                    "aadat": [
                        {
                            "id": 12,
                            "name": "DHWANI SHAH",
                            "commission": 0.5
                        }
                    ],
                    "broker": [
                        {
                            "id": 128,
                            "name": "viren ha",
                            "commission": 0.25
                        }
                    ],
                    "totalPercentage": 2.25,
                    "isVerified": true,
                    "verifiedTime": null,
                    "editTermsId": null,
                    "verifiedBy": null,
                    "editStatus": null,
                    "termName": "15DAYS (2.25) INR  DHWANI SHAH (0.5) viren ha (0.25)",
                    "accountName": "Paras Broker Buyer",
                    "currencyName": "INR",
                    "deliveryTypeName": null,
                    "dayTermsName": "15DAYS",
                    "totalPercentageFinal": 2.25
                }
            ]
        },
        {
            "id": "206",
            "categories": [
                "Aadat"
            ],
            "createdAt": "2024-01-24T08:33:53.359Z",
            "updatedAt": "2024-01-31T17:53:05.864Z",
            "name": "Ramesh Broker",
            "shortCode": "P00087",
            "birthDate": null,
            "registrationDate": null,
            "email1": "aadat@yopmail.com",
            "email2": null,
            "contactPersonName": null,
            "mobileNo": null,
            "phoneNo": null,
            "country": "101",
            "zipCode": null,
            "faxNo": null,
            "isActive": false,
            "employeeId": null,
            "companyId": "1",
            "departmentId": "1",
            "businessTypeId": null,
            "premises": null,
            "businessTypeName": null,
            "loginType": null,
            "assistantSalesPersonId": null,
            "mobileNoCc": "IN",
            "phoneNoCc": null,
            "phoneNoNdc": null,
            "faxNoNdc": null,
            "faxNoCc": null,
            "updatedByClient": null,
            "code": null,
            "codeTime": null,
            "multipleDepartmentId": null,
            "gstNo": null,
            "remark": null,
            "additionalDiscount": null,
            "additionalDiscountRound": null,
            "employee": null,
            "Country": {
                "id": "101",
                "countryName": "India"
            },
            "assistantSalesPerson": null,
            "TermsDetails": [
                {
                    "id": "138",
                    "refId": "206",
                    "currencyId": "2413",
                    "currencyPercentage": null,
                    "deliveryTypeId": null,
                    "deliveryDays": null,
                    "dayTermsId": "2465",
                    "dayTermsPercentage": 0.5,
                    "extraDollar": null,
                    "extraPercentage": null,
                    "rapPercentage": null,
                    "creditLimit": null,
                    "memoLimit": null,
                    "isDefault": true,
                    "aadat": [],
                    "broker": [
                        {
                            "id": 183,
                            "name": "Antique Diamonds",
                            "commission": 10
                        }
                    ],
                    "totalPercentage": 10.5,
                    "isVerified": true,
                    "verifiedTime": null,
                    "editTermsId": null,
                    "verifiedBy": null,
                    "editStatus": null,
                    "termName": "CASH (10.5) USD  No Aadat Antique Diamonds (10)",
                    "accountName": "Dummy Aadfdat",
                    "currencyName": "USD",
                    "deliveryTypeName": null,
                    "dayTermsName": "CASH",
                    "totalPercentageFinal": 10.5
                },
                {
                    "id": "175",
                    "refId": "206",
                    "currencyId": "2413",
                    "currencyPercentage": null,
                    "deliveryTypeId": null,
                    "deliveryDays": null,
                    "dayTermsId": "2457",
                    "dayTermsPercentage": null,
                    "extraDollar": null,
                    "extraPercentage": null,
                    "rapPercentage": null,
                    "creditLimit": null,
                    "memoLimit": null,
                    "isDefault": false,
                    "aadat": [],
                    "broker": [],
                    "totalPercentage": 0,
                    "isVerified": true,
                    "verifiedTime": null,
                    "editTermsId": null,
                    "verifiedBy": null,
                    "editStatus": false,
                    "termName": "7 DAYS (0) USD  No Aadat No Broker",
                    "accountName": "Ramesh Broker",
                    "currencyName": "USD",
                    "deliveryTypeName": null,
                    "dayTermsName": "7 DAYS",
                    "totalPercentageFinal": 0
                }
            ]
        },
        {
            "id": "185",
            "categories": [
                "LabPerson"
            ],
            "createdAt": "2024-01-19T07:10:25.564Z",
            "updatedAt": "2024-01-31T17:45:28.693Z",
            "name": "VIshal Buyer",
            "shortCode": "P00073",
            "birthDate": null,
            "registrationDate": null,
            "email1": "vd@gmail.com",
            "email2": null,
            "contactPersonName": null,
            "mobileNo": null,
            "phoneNo": null,
            "country": "3",
            "zipCode": null,
            "faxNo": null,
            "isActive": true,
            "employeeId": null,
            "companyId": null,
            "departmentId": null,
            "businessTypeId": null,
            "premises": null,
            "businessTypeName": null,
            "loginType": null,
            "assistantSalesPersonId": null,
            "mobileNoCc": "IN",
            "phoneNoCc": null,
            "phoneNoNdc": null,
            "faxNoNdc": null,
            "faxNoCc": null,
            "updatedByClient": null,
            "code": null,
            "codeTime": null,
            "multipleDepartmentId": null,
            "gstNo": null,
            "remark": null,
            "additionalDiscount": null,
            "additionalDiscountRound": null,
            "employee": null,
            "Country": {
                "id": "3",
                "countryName": "Albania"
            },
            "assistantSalesPerson": null,
            "TermsDetails": [
                {
                    "id": "104",
                    "refId": "185",
                    "currencyId": "2411",
                    "currencyPercentage": 1,
                    "deliveryTypeId": null,
                    "deliveryDays": 44,
                    "dayTermsId": "2453",
                    "dayTermsPercentage": null,
                    "extraDollar": null,
                    "extraPercentage": null,
                    "rapPercentage": null,
                    "creditLimit": null,
                    "memoLimit": null,
                    "isDefault": null,
                    "aadat": [],
                    "broker": [],
                    "totalPercentage": 1,
                    "isVerified": true,
                    "verifiedTime": null,
                    "editTermsId": null,
                    "verifiedBy": null,
                    "editStatus": null,
                    "termName": "ADVANCE BID (1) INR  No Aadat No Broker",
                    "accountName": "jhb",
                    "currencyName": "INR",
                    "deliveryTypeName": null,
                    "dayTermsName": "ADVANCE BID",
                    "totalPercentageFinal": 1
                },
                {
                    "id": "105",
                    "refId": "185",
                    "currencyId": "2411",
                    "currencyPercentage": 1,
                    "deliveryTypeId": null,
                    "deliveryDays": null,
                    "dayTermsId": "2458",
                    "dayTermsPercentage": 0.5,
                    "extraDollar": null,
                    "extraPercentage": null,
                    "rapPercentage": null,
                    "creditLimit": null,
                    "memoLimit": null,
                    "isDefault": null,
                    "aadat": [],
                    "broker": [],
                    "totalPercentage": 1.5,
                    "isVerified": true,
                    "verifiedTime": null,
                    "editTermsId": null,
                    "verifiedBy": null,
                    "editStatus": null,
                    "termName": "15DAYS (1.5) INR  No Aadat No Broker",
                    "accountName": "jhb",
                    "currencyName": "INR",
                    "deliveryTypeName": null,
                    "dayTermsName": "15DAYS",
                    "totalPercentageFinal": 1.5
                }
            ]
        },
        {
            "id": "183",
            "categories": [
                "Broker"
            ],
            "createdAt": "2024-01-19T07:04:58.233Z",
            "updatedAt": "2024-01-31T17:46:52.983Z",
            "name": "Antique Diamonds",
            "shortCode": "P00072",
            "birthDate": null,
            "registrationDate": null,
            "email1": "c@gmail.com",
            "email2": null,
            "contactPersonName": null,
            "mobileNo": null,
            "phoneNo": null,
            "country": "3",
            "zipCode": null,
            "faxNo": null,
            "isActive": true,
            "employeeId": null,
            "companyId": null,
            "departmentId": null,
            "businessTypeId": null,
            "premises": null,
            "businessTypeName": null,
            "loginType": null,
            "assistantSalesPersonId": null,
            "mobileNoCc": "IN",
            "phoneNoCc": null,
            "phoneNoNdc": null,
            "faxNoNdc": null,
            "faxNoCc": null,
            "updatedByClient": null,
            "code": null,
            "codeTime": null,
            "multipleDepartmentId": null,
            "gstNo": null,
            "remark": null,
            "additionalDiscount": null,
            "additionalDiscountRound": null,
            "employee": null,
            "Country": {
                "id": "3",
                "countryName": "Albania"
            },
            "assistantSalesPerson": null,
            "TermsDetails": [
                {
                    "id": "114",
                    "refId": "183",
                    "currencyId": "2413",
                    "currencyPercentage": null,
                    "deliveryTypeId": null,
                    "deliveryDays": null,
                    "dayTermsId": "2464",
                    "dayTermsPercentage": 0.5,
                    "extraDollar": null,
                    "extraPercentage": null,
                    "rapPercentage": null,
                    "creditLimit": null,
                    "memoLimit": null,
                    "isDefault": false,
                    "aadat": [
                        {
                            "id": 140,
                            "name": "testernews",
                            "commission": 12
                        }
                    ],
                    "broker": [],
                    "totalPercentage": 12.5,
                    "isVerified": true,
                    "verifiedTime": null,
                    "editTermsId": null,
                    "verifiedBy": null,
                    "editStatus": null,
                    "termName": "COD (12.5) USD  testernews (12) No Broker",
                    "accountName": "jhgjh",
                    "currencyName": "USD",
                    "deliveryTypeName": null,
                    "dayTermsName": "COD",
                    "totalPercentageFinal": 12.5
                },
                {
                    "id": "115",
                    "refId": "183",
                    "currencyId": "2413",
                    "currencyPercentage": null,
                    "deliveryTypeId": null,
                    "deliveryDays": null,
                    "dayTermsId": "2468",
                    "dayTermsPercentage": null,
                    "extraDollar": null,
                    "extraPercentage": null,
                    "rapPercentage": null,
                    "creditLimit": null,
                    "memoLimit": null,
                    "isDefault": false,
                    "aadat": [],
                    "broker": [],
                    "totalPercentage": 0,
                    "isVerified": true,
                    "verifiedTime": null,
                    "editTermsId": null,
                    "verifiedBy": null,
                    "editStatus": null,
                    "termName": "LC (0) USD  No Aadat No Broker",
                    "accountName": "jhgjh",
                    "currencyName": "USD",
                    "deliveryTypeName": null,
                    "dayTermsName": "LC",
                    "totalPercentageFinal": 0
                }
            ]
        },
        {
            "id": "177",
            "categories": [
                "Buyer"
            ],
            "createdAt": "2024-01-19T05:49:13.000Z",
            "updatedAt": "2024-01-24T17:47:37.470Z",
            "name": "SRK Diamonds",
            "shortCode": "P00070",
            "birthDate": "2024-01-08T00:00:00.000Z",
            "registrationDate": null,
            "email1": "fg@gmail.com",
            "email2": null,
            "contactPersonName": null,
            "mobileNo": null,
            "phoneNo": null,
            "country": "3",
            "zipCode": null,
            "faxNo": null,
            "isActive": true,
            "employeeId": null,
            "companyId": null,
            "departmentId": null,
            "businessTypeId": null,
            "premises": null,
            "businessTypeName": null,
            "loginType": null,
            "assistantSalesPersonId": null,
            "mobileNoCc": "IN",
            "phoneNoCc": null,
            "phoneNoNdc": null,
            "faxNoNdc": null,
            "faxNoCc": null,
            "updatedByClient": null,
            "code": null,
            "codeTime": null,
            "multipleDepartmentId": null,
            "gstNo": null,
            "remark": null,
            "additionalDiscount": null,
            "additionalDiscountRound": null,
            "employee": null,
            "Country": {
                "id": "3",
                "countryName": "Albania"
            },
            "assistantSalesPerson": null,
            "TermsDetails": []
        },
        {
            "id": "175",
            "categories": [
                "Employee"
            ],
            "createdAt": "2024-01-19T05:43:36.000Z",
            "updatedAt": "2024-01-24T08:55:18.034Z",
            "name": "Mega Gems",
            "shortCode": "P00069",
            "birthDate": null,
            "registrationDate": null,
            "email1": "hg@gmail.com",
            "email2": null,
            "contactPersonName": null,
            "mobileNo": null,
            "phoneNo": null,
            "country": "1",
            "zipCode": null,
            "faxNo": null,
            "isActive": true,
            "employeeId": null,
            "companyId": null,
            "departmentId": null,
            "businessTypeId": null,
            "premises": null,
            "businessTypeName": null,
            "loginType": null,
            "assistantSalesPersonId": null,
            "mobileNoCc": "IN",
            "phoneNoCc": null,
            "phoneNoNdc": null,
            "faxNoNdc": null,
            "faxNoCc": null,
            "updatedByClient": null,
            "code": null,
            "codeTime": null,
            "multipleDepartmentId": null,
            "gstNo": null,
            "remark": null,
            "additionalDiscount": null,
            "additionalDiscountRound": null,
            "employee": null,
            "Country": {
                "id": "1",
                "countryName": "Afghanistan"
            },
            "assistantSalesPerson": null,
            "TermsDetails": []
        },
        {
            "id": "137",
            "categories": [
                "Employee"
            ],
            "createdAt": "2024-01-18T05:42:27.557Z",
            "updatedAt": "2024-02-06T09:42:32.411Z",
            "name": "HRK Diamonds",
            "shortCode": "P00063",
            "birthDate": null,
            "registrationDate": null,
            "email1": "abc@gml.com",
            "email2": null,
            "contactPersonName": null,
            "mobileNo": null,
            "phoneNo": null,
            "country": "72",
            "zipCode": null,
            "faxNo": null,
            "isActive": true,
            "employeeId": null,
            "companyId": null,
            "departmentId": null,
            "businessTypeId": null,
            "premises": null,
            "businessTypeName": null,
            "loginType": null,
            "assistantSalesPersonId": null,
            "mobileNoCc": "IN",
            "phoneNoCc": null,
            "phoneNoNdc": null,
            "faxNoNdc": null,
            "faxNoCc": null,
            "updatedByClient": null,
            "code": null,
            "codeTime": null,
            "multipleDepartmentId": null,
            "gstNo": null,
            "remark": null,
            "additionalDiscount": null,
            "additionalDiscountRound": null,
            "employee": null,
            "Country": {
                "id": "72",
                "countryName": "Faroe Islands"
            },
            "assistantSalesPerson": null,
            "TermsDetails": [
                {
                    "id": "102",
                    "refId": "137",
                    "currencyId": "2411",
                    "currencyPercentage": 1,
                    "deliveryTypeId": null,
                    "deliveryDays": null,
                    "dayTermsId": "2468",
                    "dayTermsPercentage": null,
                    "extraDollar": null,
                    "extraPercentage": null,
                    "rapPercentage": null,
                    "creditLimit": null,
                    "memoLimit": null,
                    "isDefault": null,
                    "aadat": [
                        {
                            "id": 12,
                            "name": "DHWANI SHAH",
                            "commission": 5
                        }
                    ],
                    "broker": [],
                    "totalPercentage": 6,
                    "isVerified": true,
                    "verifiedTime": null,
                    "editTermsId": null,
                    "verifiedBy": null,
                    "editStatus": null,
                    "termName": "LC (6) INR  DHWANI SHAH (5) No Broker",
                    "accountName": "ttteeee",
                    "currencyName": "INR",
                    "deliveryTypeName": null,
                    "dayTermsName": "LC",
                    "totalPercentageFinal": 6
                },
                {
                    "id": "107",
                    "refId": "137",
                    "currencyId": "2411",
                    "currencyPercentage": 1,
                    "deliveryTypeId": null,
                    "deliveryDays": null,
                    "dayTermsId": "2457",
                    "dayTermsPercentage": null,
                    "extraDollar": null,
                    "extraPercentage": null,
                    "rapPercentage": null,
                    "creditLimit": null,
                    "memoLimit": null,
                    "isDefault": null,
                    "aadat": [
                        {
                            "id": 32,
                            "name": "Solanki Gems",
                            "commission": 2
                        }
                    ],
                    "broker": [],
                    "totalPercentage": 3,
                    "isVerified": true,
                    "verifiedTime": null,
                    "editTermsId": null,
                    "verifiedBy": null,
                    "editStatus": null,
                    "termName": "7 DAYS (3) INR  Solanki Gems (2) No Broker",
                    "accountName": "ttteeee",
                    "currencyName": "INR",
                    "deliveryTypeName": null,
                    "dayTermsName": "7 DAYS",
                    "totalPercentageFinal": 3
                },
                {
                    "id": "106",
                    "refId": "137",
                    "currencyId": "2412",
                    "currencyPercentage": 2.5,
                    "deliveryTypeId": null,
                    "deliveryDays": null,
                    "dayTermsId": "2459",
                    "dayTermsPercentage": 1,
                    "extraDollar": null,
                    "extraPercentage": null,
                    "rapPercentage": null,
                    "creditLimit": null,
                    "memoLimit": null,
                    "isDefault": null,
                    "aadat": [
                        {
                            "id": 32,
                            "name": "Solanki Gems",
                            "commission": 2
                        }
                    ],
                    "broker": [],
                    "totalPercentage": 5.5,
                    "isVerified": true,
                    "verifiedTime": null,
                    "editTermsId": null,
                    "verifiedBy": null,
                    "editStatus": null,
                    "termName": "30 DAYS (5.5) HKD  Solanki Gems (2) No Broker",
                    "accountName": "ttteeee",
                    "currencyName": "HKD",
                    "deliveryTypeName": null,
                    "dayTermsName": "30 DAYS",
                    "totalPercentageFinal": 5.5
                }
            ]
        },
        {
            "id": "43",
            "categories": [
                "Employee",
                "LabPerson"
            ],
            "createdAt": "2024-01-16T09:11:40.166Z",
            "updatedAt": "2024-02-11T08:00:14.937Z",
            "name": "viren ashodaria",
            "shortCode": "P00034",
            "birthDate": null,
            "registrationDate": "2024-02-05T17:58:21.845Z",
            "email1": "Maysolanki26@gmail.com",
            "email2": "Maysolanki261@gmail.com",
            "contactPersonName": "Mayursinh",
            "mobileNo": "7434926656",
            "phoneNo": null,
            "country": "3",
            "zipCode": null,
            "faxNo": null,
            "isActive": true,
            "employeeId": null,
            "companyId": null,
            "departmentId": null,
            "businessTypeId": "2188",
            "premises": null,
            "businessTypeName": null,
            "loginType": null,
            "assistantSalesPersonId": null,
            "mobileNoCc": "AL",
            "phoneNoCc": null,
            "phoneNoNdc": null,
            "faxNoNdc": null,
            "faxNoCc": null,
            "updatedByClient": null,
            "code": null,
            "codeTime": null,
            "multipleDepartmentId": [
                "SSPL-Diamond new"
            ],
            "gstNo": null,
            "remark": "jj",
            "additionalDiscount": null,
            "additionalDiscountRound": null,
            "employee": null,
            "Country": {
                "id": "3",
                "countryName": "Albania"
            },
            "assistantSalesPerson": null,
            "TermsDetails": [
                {
                    "id": "96",
                    "refId": "43",
                    "currencyId": "2412",
                    "currencyPercentage": 2.5,
                    "deliveryTypeId": null,
                    "deliveryDays": null,
                    "dayTermsId": "2457",
                    "dayTermsPercentage": null,
                    "extraDollar": null,
                    "extraPercentage": null,
                    "rapPercentage": null,
                    "creditLimit": null,
                    "memoLimit": null,
                    "isDefault": false,
                    "aadat": [],
                    "broker": [],
                    "totalPercentage": 2.5,
                    "isVerified": true,
                    "verifiedTime": null,
                    "editTermsId": null,
                    "verifiedBy": null,
                    "editStatus": null,
                    "termName": "7 DAYS (2.5) HKD  No Aadat No Broker",
                    "accountName": "viren ashodaria",
                    "currencyName": "HKD",
                    "deliveryTypeName": null,
                    "dayTermsName": "7 DAYS",
                    "totalPercentageFinal": 2.5
                },
                {
                    "id": "93",
                    "refId": "43",
                    "currencyId": "2412",
                    "currencyPercentage": 2.5,
                    "deliveryTypeId": null,
                    "deliveryDays": null,
                    "dayTermsId": "2468",
                    "dayTermsPercentage": null,
                    "extraDollar": null,
                    "extraPercentage": null,
                    "rapPercentage": null,
                    "creditLimit": null,
                    "memoLimit": null,
                    "isDefault": false,
                    "aadat": [],
                    "broker": [],
                    "totalPercentage": 2.5,
                    "isVerified": true,
                    "verifiedTime": null,
                    "editTermsId": null,
                    "verifiedBy": null,
                    "editStatus": null,
                    "termName": "LC (2.5) HKD  No Aadat No Broker",
                    "accountName": "viren ashodaria",
                    "currencyName": "HKD",
                    "deliveryTypeName": null,
                    "dayTermsName": "LC",
                    "totalPercentageFinal": 2.5
                },
                {
                    "id": "92",
                    "refId": "43",
                    "currencyId": "2412",
                    "currencyPercentage": 2.5,
                    "deliveryTypeId": null,
                    "deliveryDays": null,
                    "dayTermsId": "2468",
                    "dayTermsPercentage": null,
                    "extraDollar": null,
                    "extraPercentage": null,
                    "rapPercentage": null,
                    "creditLimit": null,
                    "memoLimit": null,
                    "isDefault": false,
                    "aadat": [],
                    "broker": [],
                    "totalPercentage": 2.5,
                    "isVerified": true,
                    "verifiedTime": null,
                    "editTermsId": null,
                    "verifiedBy": null,
                    "editStatus": null,
                    "termName": "LC (2.5) HKD  No Aadat No Broker",
                    "accountName": "viren ashodaria",
                    "currencyName": "HKD",
                    "deliveryTypeName": null,
                    "dayTermsName": "LC",
                    "totalPercentageFinal": 2.5
                },
                {
                    "id": "97",
                    "refId": "43",
                    "currencyId": "2411",
                    "currencyPercentage": 1,
                    "deliveryTypeId": null,
                    "deliveryDays": null,
                    "dayTermsId": "2464",
                    "dayTermsPercentage": 0.5,
                    "extraDollar": null,
                    "extraPercentage": null,
                    "rapPercentage": null,
                    "creditLimit": null,
                    "memoLimit": null,
                    "isDefault": false,
                    "aadat": [],
                    "broker": [],
                    "totalPercentage": 1.5,
                    "isVerified": true,
                    "verifiedTime": null,
                    "editTermsId": null,
                    "verifiedBy": null,
                    "editStatus": null,
                    "termName": "COD (1.5) INR  No Aadat No Broker",
                    "accountName": "viren ashodaria",
                    "currencyName": "INR",
                    "deliveryTypeName": null,
                    "dayTermsName": "COD",
                    "totalPercentageFinal": 1.5
                },
                {
                    "id": "95",
                    "refId": "43",
                    "currencyId": "2411",
                    "currencyPercentage": 1,
                    "deliveryTypeId": null,
                    "deliveryDays": null,
                    "dayTermsId": "2461",
                    "dayTermsPercentage": null,
                    "extraDollar": null,
                    "extraPercentage": null,
                    "rapPercentage": null,
                    "creditLimit": null,
                    "memoLimit": null,
                    "isDefault": null,
                    "aadat": [],
                    "broker": [],
                    "totalPercentage": 1,
                    "isVerified": true,
                    "verifiedTime": null,
                    "editTermsId": null,
                    "verifiedBy": null,
                    "editStatus": null,
                    "termName": "ADVANCE (1) INR  No Aadat No Broker",
                    "accountName": "viren ashodaria",
                    "currencyName": "INR",
                    "deliveryTypeName": null,
                    "dayTermsName": "ADVANCE",
                    "totalPercentageFinal": 1
                },
                {
                    "id": "94",
                    "refId": "43",
                    "currencyId": "2412",
                    "currencyPercentage": 2.5,
                    "deliveryTypeId": null,
                    "deliveryDays": null,
                    "dayTermsId": "2468",
                    "dayTermsPercentage": null,
                    "extraDollar": null,
                    "extraPercentage": null,
                    "rapPercentage": null,
                    "creditLimit": null,
                    "memoLimit": null,
                    "isDefault": false,
                    "aadat": [],
                    "broker": [],
                    "totalPercentage": 2.5,
                    "isVerified": true,
                    "verifiedTime": null,
                    "editTermsId": null,
                    "verifiedBy": null,
                    "editStatus": null,
                    "termName": "LC (2.5) HKD  No Aadat No Broker",
                    "accountName": "viren ashodaria",
                    "currencyName": "HKD",
                    "deliveryTypeName": null,
                    "dayTermsName": "LC",
                    "totalPercentageFinal": 2.5
                },
                {
                    "id": "101",
                    "refId": "43",
                    "currencyId": "2411",
                    "currencyPercentage": 1,
                    "deliveryTypeId": null,
                    "deliveryDays": null,
                    "dayTermsId": "2457",
                    "dayTermsPercentage": null,
                    "extraDollar": null,
                    "extraPercentage": null,
                    "rapPercentage": null,
                    "creditLimit": null,
                    "memoLimit": null,
                    "isDefault": false,
                    "aadat": [],
                    "broker": [],
                    "totalPercentage": 1,
                    "isVerified": true,
                    "verifiedTime": null,
                    "editTermsId": null,
                    "verifiedBy": null,
                    "editStatus": null,
                    "termName": "7 DAYS (1) INR  No Aadat No Broker",
                    "accountName": "viren ashodaria",
                    "currencyName": "INR",
                    "deliveryTypeName": null,
                    "dayTermsName": "7 DAYS",
                    "totalPercentageFinal": 1
                },
                {
                    "id": "90",
                    "refId": "43",
                    "currencyId": "2412",
                    "currencyPercentage": 2.5,
                    "deliveryTypeId": null,
                    "deliveryDays": null,
                    "dayTermsId": "2461",
                    "dayTermsPercentage": null,
                    "extraDollar": null,
                    "extraPercentage": null,
                    "rapPercentage": null,
                    "creditLimit": null,
                    "memoLimit": null,
                    "isDefault": false,
                    "aadat": [
                        {
                            "id": 41,
                            "name": "hk",
                            "commission": 23
                        }
                    ],
                    "broker": [],
                    "totalPercentage": 25.5,
                    "isVerified": true,
                    "verifiedTime": null,
                    "editTermsId": null,
                    "verifiedBy": null,
                    "editStatus": null,
                    "termName": "ADVANCE (25.5) HKD  hk (23) No Broker",
                    "accountName": "viren ashodaria",
                    "currencyName": "HKD",
                    "deliveryTypeName": null,
                    "dayTermsName": "ADVANCE",
                    "totalPercentageFinal": 25.5
                },
                {
                    "id": "91",
                    "refId": "43",
                    "currencyId": "2411",
                    "currencyPercentage": 1,
                    "deliveryTypeId": null,
                    "deliveryDays": null,
                    "dayTermsId": "2461",
                    "dayTermsPercentage": null,
                    "extraDollar": null,
                    "extraPercentage": null,
                    "rapPercentage": null,
                    "creditLimit": null,
                    "memoLimit": null,
                    "isDefault": false,
                    "aadat": [],
                    "broker": [],
                    "totalPercentage": 1,
                    "isVerified": true,
                    "verifiedTime": null,
                    "editTermsId": null,
                    "verifiedBy": null,
                    "editStatus": null,
                    "termName": "ADVANCE (1) INR  No Aadat No Broker",
                    "accountName": "viren ashodaria",
                    "currencyName": "INR",
                    "deliveryTypeName": null,
                    "dayTermsName": "ADVANCE",
                    "totalPercentageFinal": 1
                },
                {
                    "id": "111",
                    "refId": "43",
                    "currencyId": "2413",
                    "currencyPercentage": null,
                    "deliveryTypeId": null,
                    "deliveryDays": null,
                    "dayTermsId": "2464",
                    "dayTermsPercentage": 0.5,
                    "extraDollar": null,
                    "extraPercentage": null,
                    "rapPercentage": null,
                    "creditLimit": null,
                    "memoLimit": null,
                    "isDefault": true,
                    "aadat": [],
                    "broker": [
                        {
                            "id": 38,
                            "name": "tester",
                            "commission": 2
                        }
                    ],
                    "totalPercentage": 2.5,
                    "isVerified": true,
                    "verifiedTime": null,
                    "editTermsId": null,
                    "verifiedBy": null,
                    "editStatus": null,
                    "termName": "COD (2.5) USD  No Aadat tester (2)",
                    "accountName": "viren ashodaria",
                    "currencyName": "USD",
                    "deliveryTypeName": null,
                    "dayTermsName": "COD",
                    "totalPercentageFinal": 2.5
                },
                {
                    "id": "98",
                    "refId": "43",
                    "currencyId": "2412",
                    "currencyPercentage": 2.5,
                    "deliveryTypeId": null,
                    "deliveryDays": null,
                    "dayTermsId": "2459",
                    "dayTermsPercentage": 1,
                    "extraDollar": null,
                    "extraPercentage": null,
                    "rapPercentage": null,
                    "creditLimit": null,
                    "memoLimit": null,
                    "isDefault": false,
                    "aadat": [
                        {
                            "id": 33,
                            "name": "Paras",
                            "commission": 2
                        }
                    ],
                    "broker": [],
                    "totalPercentage": 5.5,
                    "isVerified": true,
                    "verifiedTime": null,
                    "editTermsId": null,
                    "verifiedBy": null,
                    "editStatus": null,
                    "termName": "30 DAYS (5.5) HKD  Paras (2) No Broker",
                    "accountName": "viren ashodaria",
                    "currencyName": "HKD",
                    "deliveryTypeName": null,
                    "dayTermsName": "30 DAYS",
                    "totalPercentageFinal": 5.5
                },
                {
                    "id": "168",
                    "refId": "43",
                    "currencyId": "2412",
                    "currencyPercentage": 2.5,
                    "deliveryTypeId": null,
                    "deliveryDays": null,
                    "dayTermsId": "2461",
                    "dayTermsPercentage": null,
                    "extraDollar": null,
                    "extraPercentage": null,
                    "rapPercentage": null,
                    "creditLimit": null,
                    "memoLimit": null,
                    "isDefault": false,
                    "aadat": [],
                    "broker": [],
                    "totalPercentage": 2.5,
                    "isVerified": true,
                    "verifiedTime": null,
                    "editTermsId": null,
                    "verifiedBy": null,
                    "editStatus": null,
                    "termName": "ADVANCE (2.5) HKD  No Aadat No Broker",
                    "accountName": "viren ashodaria",
                    "currencyName": "HKD",
                    "deliveryTypeName": null,
                    "dayTermsName": "ADVANCE",
                    "totalPercentageFinal": 2.5
                },
                {
                    "id": "100",
                    "refId": "43",
                    "currencyId": "2413",
                    "currencyPercentage": null,
                    "deliveryTypeId": null,
                    "deliveryDays": null,
                    "dayTermsId": "2468",
                    "dayTermsPercentage": null,
                    "extraDollar": null,
                    "extraPercentage": null,
                    "rapPercentage": null,
                    "creditLimit": null,
                    "memoLimit": null,
                    "isDefault": false,
                    "aadat": [
                        {
                            "id": 33,
                            "name": "Paras",
                            "commission": 12
                        }
                    ],
                    "broker": [],
                    "totalPercentage": 12,
                    "isVerified": true,
                    "verifiedTime": null,
                    "editTermsId": null,
                    "verifiedBy": null,
                    "editStatus": null,
                    "termName": "LC (12) USD  Paras (12) No Broker",
                    "accountName": "viren ashodaria",
                    "currencyName": "USD",
                    "deliveryTypeName": null,
                    "dayTermsName": "LC",
                    "totalPercentageFinal": 12
                },
                {
                    "id": "89",
                    "refId": "43",
                    "currencyId": "2412",
                    "currencyPercentage": 2.5,
                    "deliveryTypeId": null,
                    "deliveryDays": null,
                    "dayTermsId": "2461",
                    "dayTermsPercentage": null,
                    "extraDollar": null,
                    "extraPercentage": null,
                    "rapPercentage": null,
                    "creditLimit": null,
                    "memoLimit": null,
                    "isDefault": false,
                    "aadat": [
                        {
                            "id": 140,
                            "name": "testernews",
                            "commission": 2
                        }
                    ],
                    "broker": [],
                    "totalPercentage": 4.5,
                    "isVerified": true,
                    "verifiedTime": null,
                    "editTermsId": null,
                    "verifiedBy": null,
                    "editStatus": null,
                    "termName": "ADVANCE (4.5) HKD  testernews (2) No Broker",
                    "accountName": "viren ashodaria",
                    "currencyName": "HKD",
                    "deliveryTypeName": null,
                    "dayTermsName": "ADVANCE",
                    "totalPercentageFinal": 4.5
                },
                {
                    "id": "99",
                    "refId": "43",
                    "currencyId": "2412",
                    "currencyPercentage": 2.5,
                    "deliveryTypeId": null,
                    "deliveryDays": null,
                    "dayTermsId": "2453",
                    "dayTermsPercentage": null,
                    "extraDollar": null,
                    "extraPercentage": null,
                    "rapPercentage": null,
                    "creditLimit": null,
                    "memoLimit": null,
                    "isDefault": false,
                    "aadat": [],
                    "broker": [],
                    "totalPercentage": 2.5,
                    "isVerified": true,
                    "verifiedTime": null,
                    "editTermsId": null,
                    "verifiedBy": null,
                    "editStatus": null,
                    "termName": "ADVANCE BID (2.5) HKD  No Aadat No Broker",
                    "accountName": "viren ashodaria",
                    "currencyName": "HKD",
                    "deliveryTypeName": null,
                    "dayTermsName": "ADVANCE BID",
                    "totalPercentageFinal": 2.5
                }
            ]
        }
    ]
